INSERT INTO `informacion_personal` (`nickname`, `nombre_completo`) VALUES
('GIANCARLOVILCH', 'Gian Carlo, Vilcamiche Chávez'),
('SOLANGECC', 'Solange Moulin, Coronel Camacllanqui'),
('MILAGROSHC', 'Milagros Del Pilar, Huamán Cruzado'),
('DARIANABC', 'Dariana, Bautista Contreras'),
('PATRICIAOP', 'Patricia del Pilar, Obregon Pozo'),
('MARYORIFU', 'Maryori, Flores Ubaldo'),
('MARIBELSB', 'Maribel Rosario, Salazar Baldeon'),
('MARIAGT', 'María Doris, García Torres'),
('FLORMH', 'Flor de maria, Mercedes huayta'),
('KARENME', 'Karen Lizbeth, Martinez Encina'),
('FIORELLACR', 'Fiorella del Rosario, Chambi Rafaile'),
('SHARIKRP', 'Sharik Sheylly, Rodriguez Pineda'),
('MONICAQC', 'Monica, Quispe Ccallo'),
('KARINRC', 'Karin Gianina, Ramirez Calixto'),
('LEIDIPC', 'Leidi, Peralta Colunche'),
('DIANAMH', 'Diana, Mendoza Huaman'),
('GERALDINNEQA', 'Rocío Geraldinne, Quispe Alberco'),
('GUILLERMINASB', 'Guillermina Yomnis, Santos Basilio'),
('ELIZABETHFS', 'Elizabeth, Flores Silva'),
('MARINAHA', 'Marina, Heredia Acuña'),
('ALEXANDERSC', 'Alexander Rafael, Suarez Chacón'),
('YOLVIPF', 'Yolvi Romelia, Patricio Flores'),
('INOEOQ', 'Inoe Ortiz Quispe, Inoe'),
('SHEILAMC', 'Sheila, Marcos Chagua'),
('ELENAPM', 'Elena Dayana, Peña Manrique'),
('DILZAAM', 'Dilza Elizabeth, Alarcon Muñoz'),
('SHARONMA', 'Sharon Candy, Marcos Alfaro'),
('MIRIAMAB', 'Miriam oriana, Aguirre borja'),
('YENIFERQL', 'Yenifer Katia, Quispe Llacchua'),
('LIZBETHQ', 'Lizbeth, Quispe de la cruz'),
('YOSELINBS', 'Yoselin Margarita, Baldera Siesquén'),
('GAVISA', 'Gavi, Santos ascencio'),
('ROYVC', 'Roy Anthony, Vilcamiche Chavez'),
('LORELISZ', 'Loreli Elizabeth, Salas Zuñiga'),
('NAYELIBE', 'Nayeli, Benancio Espinoza'),
('ROSARIOFE', 'Geraldine Rosario, Felices Escobar'),
('ANALUFF', 'Analu, Fonseca Fernández'),
('DELINAGM', 'DELINA, GUILLEN MATOS'),
('LISSETBD', 'Lisset, Bonifacio Duran'),
('ANACM', 'Ana Lucia, Coaquira Mamani'),
('JHOVANISC', 'Jhovani, Suarez Cueva'),
('CAROLACR', 'Carola liz, Carhuaricra reyes'),
('LUISSG', 'Luis Daryl, Sanchez Garcia'),
('CARMENGG', 'Carmen esmeralda, Guadalupe Galarza'),
('ERIKAGH', 'Erika Yuliana, Guerrero Huerta');


INSERT INTO `usuarios` (`nickname`, `password`) VALUES
('GIANCARLOVILCH', '$2y$10$/fFVChDsLvnMX4F9pzeDxeVmHjlakhgcZx0oput8m7vvGO14pwi5.'),
('SOLANGECC', '$2y$10$H9HkCkVtQaBIk8arZ6k07.8cgq56x6WwWr2rZo6CMRj9BcuuBqRiK'),
('DARIANABC', '$2y$10$4c.WD6S76Aaw0tD667FcNeZCcsWfN6REyOIBBhMZNLZ4P9773s3ry'),
('PATRICIAOP', '$2y$10$bw5xVYFmHTl3HWu8kthwW.U8XMnktRqpsNm4DX8HBqpA6AJkikJcW'),
('MARYORIFU', '$2y$10$h0XYDrQFOWfWDA3zM/v/Fufdn3ITb2zoecFmE3/c4DgLhD9qiT1Sm'),
('MARIBELSB', '$2y$10$ngz3.Xq2H1uKAxBCcuoC3.mVhUz9gFfNIHcql93X8XneYn.NWH78K'),
('FLORMH', '$2y$10$0NCiTBK8RIz6cfQe8p0bNOIkLkcO3ofMZirr8O7uMBOfHx78C7J7a'),
('KARENME', '$2y$10$iMuQAOLoQIKfuU/lyEeq8eAwPf3oAq0eNhMPRFOYb/acY/KK.q1Bi'),
('FIORELLACR', '$2y$10$KpMXh7SVVwEKbgpIHpBMK..07r.V4Zr9plT09zNuO95FYytKEipMq'),
('SHARIKRP', '$2y$10$EmzfS.lzizd9.g/OlQxzr.nL0QRvJ4aB.XkbfuFHjeSb9qeCZYZTe'),
('MONICAQC', '$2y$10$0horK6agcqMzGulZcXl09.MybTFsiyud1/27bnxJKNGfurtppq1Ky'),
('DIANAMH', '$2y$10$2N1AvWu2w9J/2BZIeBOO8.Rt8LdUKOIaVgQDWv5ELuAGVHbhJTCvu'),
('GERALDINNEQA', '$2y$10$oq9d8ywlS6ZWa/xFixghzuQnWvy2/Ov0l3HBI9LyEgND/.c109RRy'),
('YOLVIPF', '$2y$10$hGof6wgfx5W3MKmCiLoXpeO4l2AUJW22WerbYTA23/p4eWhWTXBAS'),
('ALEXANDERSC', '$2y$10$eF5XE/hmN6eOT3s4/PWinenQUfWdlRq3G1TEfdpSstwrlfjdgZpSq'),
('SHARONMA', '$2y$10$EfwlI1XDk72tvfi8FaAN.OZIiG4b4WSW5wxK7e0TnmNySAx9Qmxvq'),
('YENIFERQL', '$2y$10$eeK7zwHVysdt5Kp0J3qpp.riRTjQJRPk.xTbCjRCpG3m1sskN0osG'),
('ROYVC', '$2y$10$4yZAxjs97JcsgQ5Fi8fCJ.VNqr1mwY/TpyltlAa.qWtTvqYbH4sWC'),
('NAYELIBE', '$2y$10$BXzeK1.54rxkS0myBJWpNe6xMlqM8gPZHsVwRFbxVh63Cf7nlnFGe'),
('JHOVANISC', '$2y$10$.V5wVOjPO.mpdIvY6MqS8en.Mte9JJVOOWQAiitAz7JvEJ5XejR3e'),
('CAROLACR', '$2y$10$7YitjfHJVLiexNh6w0l1oeGghiXEzxPOZCuYQgmh3OpDQoa2VR0PS'),
('LUISSG', '$2y$10$g1USCSrqYnXoYv3MJ/fTEeLD82mf5secSJmXK/EhQq28Fw0kXE4O.'),
('ERIKAGH', '$2y$10$JBWbSvEH2k2/Oj6PIxgAOOgiAoSBCXlKxcBKcWfwQJKLXgwoVl4mi');



